# Generated by Django 5.2 on 2025-07-31 20:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myyandex', '0003_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Подробное описание'),
        ),
    ]
